### ISSUE TITLE
IE11 - Edit DOI causes glimmer error.

### ISSUE THREAD

**Issue by richardhallett** [datacite/bracco#45]
When attempting to edit a DOI on IE11 JS errors get produced causing the application to no longer work correctly.

Error:
Error: a glimmer transaction was begun, but one already exists. You may have a nested transaction
   at e.assert (https://doi.test.datacite.org/assets/vendor-de7f8e8f10b5e03e90cd797a8fb68627.js:2291:80)
   at e.prototype.begin (https://doi.test.datacite.org/assets/vendor-de7f8e8f10b5e03e90cd797a8fb68627.js:2200:422)
   at i.prototype.begin (https://doi.test.datacite.org/assets/vendor-de7f8e8f10b5e03e90cd797a8fb68627.js:2759:227)
   at e.prototype._renderRoots (https://doi.test.datacite.org/assets/vendor-de7f8e8f10b5e03e90cd797a8fb68627.js:2888:8)
   at e.prototype._renderRootsTransaction (https://doi.test.datacite.org/assets/vendor-de7f8e8f10b5e03e90cd797a8fb68627.js:2893:5)
   at e.prototype._revalidate (https://doi.test.datacite.org/assets/vendor-de7f8e8f10b5e03e90cd797a8fb68627.js:2895:332)
   at e.prototype.invokeWithOnError (https://doi.test.datacite.org/assets/vendor-de7f8e8f10b5e03e90cd797a8fb68627.js:2326:248)
   at e.prototype.flush (https://doi.test.datacite.org/assets/vendor-de7f8e8f10b5e03e90cd797

Reproduce:
1. Click DOI's
2. Choose any DOI.
3. Click Edit DOI.

**Comment by richardhallett** [comment]
This should be reassessed when doi registration functionality is re-worked.
